package com.netcattest.ncatminecraft.client.remote;

final class RemoteScanCodes {
    private RemoteScanCodes() {
    }

    static int fromCode(String code) {
        if (code == null) return 0;
        return switch (code) {
            case "Escape" -> 0x01;
            case "Digit1" -> 0x02;
            case "Digit2" -> 0x03;
            case "Digit3" -> 0x04;
            case "Digit4" -> 0x05;
            case "Digit5" -> 0x06;
            case "Digit6" -> 0x07;
            case "Digit7" -> 0x08;
            case "Digit8" -> 0x09;
            case "Digit9" -> 0x0A;
            case "Digit0" -> 0x0B;
            case "Minus" -> 0x0C;
            case "Equal" -> 0x0D;
            case "Backspace" -> 0x0E;
            case "Tab" -> 0x0F;
            case "KeyQ" -> 0x10;
            case "KeyW" -> 0x11;
            case "KeyE" -> 0x12;
            case "KeyR" -> 0x13;
            case "KeyT" -> 0x14;
            case "KeyY" -> 0x15;
            case "KeyU" -> 0x16;
            case "KeyI" -> 0x17;
            case "KeyO" -> 0x18;
            case "KeyP" -> 0x19;
            case "BracketLeft" -> 0x1A;
            case "BracketRight" -> 0x1B;
            case "Enter" -> 0x1C;
            case "ControlLeft" -> 0x1D;
            case "KeyA" -> 0x1E;
            case "KeyS" -> 0x1F;
            case "KeyD" -> 0x20;
            case "KeyF" -> 0x21;
            case "KeyG" -> 0x22;
            case "KeyH" -> 0x23;
            case "KeyJ" -> 0x24;
            case "KeyK" -> 0x25;
            case "KeyL" -> 0x26;
            case "Semicolon" -> 0x27;
            case "Quote" -> 0x28;
            case "Backquote" -> 0x29;
            case "ShiftLeft" -> 0x2A;
            case "Backslash", "IntlBackslash" -> 0x2B;
            case "KeyZ" -> 0x2C;
            case "KeyX" -> 0x2D;
            case "KeyC" -> 0x2E;
            case "KeyV" -> 0x2F;
            case "KeyB" -> 0x30;
            case "KeyN" -> 0x31;
            case "KeyM" -> 0x32;
            case "Comma" -> 0x33;
            case "Period" -> 0x34;
            case "Slash" -> 0x35;
            case "ShiftRight" -> 0x36;
            case "NumpadMultiply" -> 0x37;
            case "AltLeft" -> 0x38;
            case "Space" -> 0x39;
            case "CapsLock" -> 0x3A;
            case "F1" -> 0x3B;
            case "F2" -> 0x3C;
            case "F3" -> 0x3D;
            case "F4" -> 0x3E;
            case "F5" -> 0x3F;
            case "F6" -> 0x40;
            case "F7" -> 0x41;
            case "F8" -> 0x42;
            case "F9" -> 0x43;
            case "F10" -> 0x44;
            case "NumLock" -> 0x45;
            case "ScrollLock" -> 0x46;
            case "Numpad7" -> 0x47;
            case "Numpad8" -> 0x48;
            case "Numpad9" -> 0x49;
            case "NumpadSubtract" -> 0x4A;
            case "Numpad4" -> 0x4B;
            case "Numpad5" -> 0x4C;
            case "Numpad6" -> 0x4D;
            case "NumpadAdd" -> 0x4E;
            case "Numpad1" -> 0x4F;
            case "Numpad2" -> 0x50;
            case "Numpad3" -> 0x51;
            case "Numpad0" -> 0x52;
            case "NumpadDecimal" -> 0x53;
            case "IntlRo" -> 0x73;
            case "F11" -> 0x57;
            case "F12" -> 0x58;
            case "NumpadEnter" -> 0x11C;
            case "ControlRight" -> 0x11D;
            case "NumpadDivide" -> 0x135;
            case "AltRight" -> 0x138;
            case "Home" -> 0x147;
            case "ArrowUp" -> 0x148;
            case "PageUp" -> 0x149;
            case "ArrowLeft" -> 0x14B;
            case "ArrowRight" -> 0x14D;
            case "End" -> 0x14F;
            case "ArrowDown" -> 0x150;
            case "PageDown" -> 0x151;
            case "Insert" -> 0x152;
            case "Delete" -> 0x153;
            case "MetaLeft" -> 0x15B;
            case "MetaRight" -> 0x15C;
            case "ContextMenu" -> 0x15D;
            default -> 0;
        };
    }
}
